version: '3.9'

services:
  vania:
    build: .
    image: vania/app:latest
    container_name: vania
    restart: always
    volumes:
      - app:/app
      - ./public:/public
      - ./storage:/storage
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: "postgresql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "bling"
      DB_USERNAME: "bling"
      DB_PASSWORD: "bling"
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg16
    container_name: bling-postgres
    restart: always
    environment:
      POSTGRES_DB: "bling"
      POSTGRES_USER: "bling"
      POSTGRES_PASSWORD: "bling"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  app:
  postgres_data:
