version: '3.9'

services:
  vania:
    build: .
    image: vania/app:latest
    container_name: vania
    restart: always
    volumes:
      - app:/app
      - ./public:/public
      - ./storage:/storage
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: "http://qdrant:6333"
      QDRANT_POSTS_COLLECTION: "feed_posts"
      QDRANT_VECTOR_SIZE: "256"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  app:
  qdrant_storage:
