name: bling
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  get_it: ^8.0.3
  uuid: ^4.5.1
  vania: ^0.7.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
#dependency_overrides:
#  pointycastle: 3.7.3
