class LocationScopeHelper {
  static const List<String> continents = <String>[
    'Africa',
    'Europe',
    'Asia',
    'North America',
    'South America',
    'Oceania',
    'Antarctica',
  ];

  static String normalizeText(String value) {
    final trimmed = value.trim();
    if (trimmed.isEmpty) return '';
    final collapsed = trimmed.replaceAll(RegExp(r'\s+'), ' ');
    return collapsed;
  }

  static String normalizeKey(String value) {
    return normalizeText(value).toLowerCase();
  }

  static String normalizeCountryCode(String value) {
    return value.trim().toUpperCase();
  }

  static String? continentForCountryCode(String value) {
    final code = normalizeCountryCode(value);
    if (code.isEmpty) return null;
    return _countryCodeToContinent[code];
  }

  static String? continentForCountryName(String value) {
    final key = normalizeKey(value);
    if (key.isEmpty) return null;
    final code = _countryNameToCode[key];
    if (code == null) return null;
    return _countryCodeToContinent[code];
  }

  static String resolveContinent({
    required String explicitContinent,
    required String countryCode,
    required String country,
  }) {
    final explicit = normalizeText(explicitContinent);
    if (explicit.isNotEmpty) return explicit;
    final fromCode = continentForCountryCode(countryCode);
    if (fromCode != null) return fromCode;
    final fromCountry = continentForCountryName(country);
    return fromCountry ?? '';
  }

  static bool matchesLocationTarget({
    required String target,
    required String actual,
  }) {
    if (target.trim().isEmpty) return true;
    if (actual.trim().isEmpty) return false;
    return normalizeKey(target) == normalizeKey(actual);
  }

  static const Map<String, String> _countryCodeToContinent = <String, String>{
    'DZ': 'Africa',
    'AO': 'Africa',
    'BJ': 'Africa',
    'BW': 'Africa',
    'BF': 'Africa',
    'BI': 'Africa',
    'CM': 'Africa',
    'CV': 'Africa',
    'CF': 'Africa',
    'TD': 'Africa',
    'KM': 'Africa',
    'CG': 'Africa',
    'CD': 'Africa',
    'CI': 'Africa',
    'DJ': 'Africa',
    'EG': 'Africa',
    'GQ': 'Africa',
    'ER': 'Africa',
    'SZ': 'Africa',
    'ET': 'Africa',
    'GA': 'Africa',
    'GM': 'Africa',
    'GH': 'Africa',
    'GN': 'Africa',
    'GW': 'Africa',
    'KE': 'Africa',
    'LS': 'Africa',
    'LR': 'Africa',
    'LY': 'Africa',
    'MG': 'Africa',
    'MW': 'Africa',
    'ML': 'Africa',
    'MR': 'Africa',
    'MU': 'Africa',
    'YT': 'Africa',
    'MA': 'Africa',
    'MZ': 'Africa',
    'NA': 'Africa',
    'NE': 'Africa',
    'NG': 'Africa',
    'RE': 'Africa',
    'RW': 'Africa',
    'SH': 'Africa',
    'ST': 'Africa',
    'SN': 'Africa',
    'SC': 'Africa',
    'SL': 'Africa',
    'SO': 'Africa',
    'ZA': 'Africa',
    'SS': 'Africa',
    'SD': 'Africa',
    'TZ': 'Africa',
    'TG': 'Africa',
    'TN': 'Africa',
    'UG': 'Africa',
    'EH': 'Africa',
    'ZM': 'Africa',
    'ZW': 'Africa',
    'AL': 'Europe',
    'AD': 'Europe',
    'AM': 'Europe',
    'AT': 'Europe',
    'AZ': 'Europe',
    'BY': 'Europe',
    'BE': 'Europe',
    'BA': 'Europe',
    'BG': 'Europe',
    'HR': 'Europe',
    'CY': 'Europe',
    'CZ': 'Europe',
    'DK': 'Europe',
    'EE': 'Europe',
    'FO': 'Europe',
    'FI': 'Europe',
    'FR': 'Europe',
    'GE': 'Europe',
    'DE': 'Europe',
    'GI': 'Europe',
    'GR': 'Europe',
    'GL': 'Europe',
    'GG': 'Europe',
    'HU': 'Europe',
    'IS': 'Europe',
    'IE': 'Europe',
    'IM': 'Europe',
    'IT': 'Europe',
    'JE': 'Europe',
    'KZ': 'Europe',
    'XK': 'Europe',
    'LV': 'Europe',
    'LI': 'Europe',
    'LT': 'Europe',
    'LU': 'Europe',
    'MT': 'Europe',
    'MD': 'Europe',
    'MC': 'Europe',
    'ME': 'Europe',
    'NL': 'Europe',
    'MK': 'Europe',
    'NO': 'Europe',
    'PL': 'Europe',
    'PT': 'Europe',
    'RO': 'Europe',
    'RU': 'Europe',
    'SM': 'Europe',
    'RS': 'Europe',
    'SK': 'Europe',
    'SI': 'Europe',
    'ES': 'Europe',
    'SJ': 'Europe',
    'SE': 'Europe',
    'CH': 'Europe',
    'TR': 'Europe',
    'UA': 'Europe',
    'GB': 'Europe',
    'VA': 'Europe',
    'AF': 'Asia',
    'BH': 'Asia',
    'BD': 'Asia',
    'BT': 'Asia',
    'BN': 'Asia',
    'KH': 'Asia',
    'CN': 'Asia',
    'HK': 'Asia',
    'MO': 'Asia',
    'IN': 'Asia',
    'ID': 'Asia',
    'IR': 'Asia',
    'IQ': 'Asia',
    'IL': 'Asia',
    'JP': 'Asia',
    'JO': 'Asia',
    'KP': 'Asia',
    'KR': 'Asia',
    'KW': 'Asia',
    'KG': 'Asia',
    'LA': 'Asia',
    'LB': 'Asia',
    'MY': 'Asia',
    'MV': 'Asia',
    'MN': 'Asia',
    'MM': 'Asia',
    'NP': 'Asia',
    'OM': 'Asia',
    'PK': 'Asia',
    'PS': 'Asia',
    'PH': 'Asia',
    'QA': 'Asia',
    'SA': 'Asia',
    'SG': 'Asia',
    'LK': 'Asia',
    'SY': 'Asia',
    'TW': 'Asia',
    'TJ': 'Asia',
    'TH': 'Asia',
    'TL': 'Asia',
    'TM': 'Asia',
    'AE': 'Asia',
    'UZ': 'Asia',
    'VN': 'Asia',
    'YE': 'Asia',
    'CA': 'North America',
    'US': 'North America',
    'MX': 'North America',
    'BZ': 'North America',
    'CR': 'North America',
    'SV': 'North America',
    'GT': 'North America',
    'HN': 'North America',
    'NI': 'North America',
    'PA': 'North America',
    'AG': 'North America',
    'BS': 'North America',
    'BB': 'North America',
    'CU': 'North America',
    'DM': 'North America',
    'DO': 'North America',
    'GD': 'North America',
    'HT': 'North America',
    'JM': 'North America',
    'KN': 'North America',
    'LC': 'North America',
    'VC': 'North America',
    'TT': 'North America',
    'AR': 'South America',
    'BO': 'South America',
    'BR': 'South America',
    'CL': 'South America',
    'CO': 'South America',
    'EC': 'South America',
    'FK': 'South America',
    'GF': 'South America',
    'GY': 'South America',
    'PY': 'South America',
    'PE': 'South America',
    'SR': 'South America',
    'UY': 'South America',
    'VE': 'South America',
    'AU': 'Oceania',
    'NZ': 'Oceania',
    'FJ': 'Oceania',
    'PG': 'Oceania',
    'SB': 'Oceania',
    'VU': 'Oceania',
    'NC': 'Oceania',
    'PF': 'Oceania',
    'WS': 'Oceania',
    'TO': 'Oceania',
    'KI': 'Oceania',
    'TV': 'Oceania',
    'NR': 'Oceania',
    'FM': 'Oceania',
    'MH': 'Oceania',
    'PW': 'Oceania',
    'AQ': 'Antarctica',
  };

  static final Map<String, String> _countryNameToCode = <String, String>{
    'kenya': 'KE',
    'uganda': 'UG',
    'tanzania': 'TZ',
    'rwanda': 'RW',
    'burundi': 'BI',
    'south africa': 'ZA',
    'nigeria': 'NG',
    'ghana': 'GH',
    'egypt': 'EG',
    'morocco': 'MA',
    'algeria': 'DZ',
    'tunisia': 'TN',
    'ethiopia': 'ET',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    'united states': 'US',
    'united states of america': 'US',
    'canada': 'CA',
    'mexico': 'MX',
    'brazil': 'BR',
    'argentina': 'AR',
    'colombia': 'CO',
    'chile': 'CL',
    'peru': 'PE',
    'united kingdom': 'GB',
    'great britain': 'GB',
    'england': 'GB',
    'france': 'FR',
    'germany': 'DE',
    'italy': 'IT',
    'spain': 'ES',
    'portugal': 'PT',
    'netherlands': 'NL',
    'belgium': 'BE',
    'switzerland': 'CH',
    'sweden': 'SE',
    'norway': 'NO',
    'denmark': 'DK',
    'ireland': 'IE',
    'poland': 'PL',
    'romania': 'RO',
    'ukraine': 'UA',
    'russia': 'RU',
    'turkey': 'TR',
    'india': 'IN',
    'pakistan': 'PK',
    'bangladesh': 'BD',
    'china': 'CN',
    'japan': 'JP',
    'south korea': 'KR',
    'indonesia': 'ID',
    'philippines': 'PH',
    'thailand': 'TH',
    'singapore': 'SG',
    'malaysia': 'MY',
    'united arab emirates': 'AE',
    'saudi arabia': 'SA',
    'qatar': 'QA',
    'israel': 'IL',
    'australia': 'AU',
    'new zealand': 'NZ',
  };
}
